P01/force-app/main/default/objects/VipAppointment__c/VipAppointment__c.object-meta.xml
<CustomObject>
    <label>VipAppointment</label>
    <nameField>
        <label>VipAppointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VipAppointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/VipAppointment__c/fields/DateTime__c.field-meta.xml
<CustomField>
    <fullName>DateTime__c</fullName>
    <description>DateTime of appointment</description>
    <label>DateTime</label>
    <type>DateTime</type>
</CustomField>

P01/force-app/main/default/classes/AboutUsController.cls
public with sharing class AboutUsController {

    @AuraEnabled
    public static Boolean AppointmentMaker(String FirstName, String LastName, String Inspiration, DateTime AppointmentDate){
        String Fullname = FirstName+LastName;
        VipAppointment__c Appointment = new VipAppointment__c(Name=Fullname, DateTime__c = AppointmentDate);
        database.insert(Appointment);
        System.debug(Appointment);

        return true;

    }
	
}