P01/force-app/main/default/objects/VipAppointment__c/VipAppointment__c.object-meta.xml
<CustomObject>
    <label>VipAppointment</label>
    <nameField>
        <label>VipAppointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VipAppointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/VipAppointment__c/fields/DateTime__c.field-meta.xml
<CustomField>
    <fullName>DateTime__c</fullName>
    <description>DateTime of appointment</description>
    <label>DateTime</label>
    <type>DateTime</type>
</CustomField>

P01/force-app/main/default/objects/VipAppointment__c/fields/Inspiration__c.field-meta.xml
<CustomField>
    <fullName>Inspiration__c</fullName>
    <label>Inspiration</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

P01/force-app/main/default/classes/AboutUsControllerTester.cls
@isTest
public with sharing class AboutUsControllerTester {

    //variable declarations
    static string MockAppointmentName = 'John Cleese';
    static string MockInspiration = 'To acquire the finest cheese London has to offer.';
    static Datetime MockAppointmentDateTime = DateTime.newInstance(1997, 1, 31, 7, 8, 16);
   

    @TestSetup
    static void makeData(){
        
        //Create a new VipAppointment Record
        VipAppointment__c MockAppointment = new VipAppointment__c();
        MockAppointment.Name = MockAppointmentName;
        MockAppointment.DateTime__c = MockAppointmentDateTime;
        MockAppointment.Inspiration__c = MockInspiration;

        INSERT MockAppointment;
    }

    @isTest
    public static void AppointmentMakerTester(){
        Test.startTest();
        string testedFirstName = 'John';
        string testedLastName ='Cleese';
        string testedName ='John Cleese';
        string testedInspiration = 'To acquire the finest cheese London has to offer.';
        Datetime testedDateTime = DateTime.newInstance(1997, 1, 31, 7, 8, 16);
        Boolean result = AboutUsController.AppointmentMaker(testedFirstName, testedLastName, testedInspiration, testedDateTime );
        Boolean testMarker = false;
        
        VipAppointment__c AppointmentActual = [SELECT id, name, DateTime__c, Inspiration__c FROM VipAppointment__c WHERE name=:testedName LIMIT 1];
        if(AppointmentActual.name==testedName){
            testMarker = true;
        }

        System.assertEquals(result, testMarker);

        Test.StopTest();


    }
}