P01/force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>Sale</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Sales Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/Sales__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

Project01/force-app/main/default/objects/Sales__c/fields/Sale_Date__c.field-meta.xml
<CustomField>
    <fullName>Sale_Date__c</fullName>
    <label>Sale Date</label>
    <type>DateTime</type>
</CustomField>

Project-01/force-app/main/default/objects/Sales__c/fields/Sales_Associate_Id__c.field-meta.xml
<CustomField>
    <fullName>Sales_Associate_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Associate</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

Project01/force-app/main/default/objects/Sales__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project01/force-app/main/default/objects/Sales__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

P01/force-app/main/default/classes/SalesController.cls
public class SalesController {
    List<Sales__c> salesList = [SELECT Id, Name, Account_Name__c, Sale_Date__c, Status__c, Total__c, Sales_Associate_Id__c FROM Sales__c WHERE Account_Name__C = :ApexPages.currentPage().getParameters().get('name') ORDER BY Sale_Date__c DESC LIMIT 10];
    //,(SELECT T_J_Product__c.Description__c FROM Sales_item__r )
    public List<Sales__c> getsalesList(){
        return salesList;
    }
    public PageReference save(){
        update salesList;
        return null;
    }

}