Project01/force-app/main/default/objects/ProductTJ__c/ProductTJ__c.object-meta.xml
<CustomObject>
    <description>my custom product object</description>
    <label>T&amp;J Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product SKU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;J Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/ProductTJ__c/fields/Retail_Price1__c.field-meta.xml
<CustomField>
    <fullName>Retail_Price1__c</fullName>
    <label>Retail Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project01/force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>Sale</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Sales Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/Sales__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

Project01/force-app/main/default/objects/Sales__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project01/force-app/main/default/objects/Sales__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project-01/force-app/main/default/objects/Sales_item__c/Sales_item__c.object-meta.xml
<CustomObject>
    <label>Sales item</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sales item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project-01/force-app/main/default/objects/Sales_item__c/fields/Retail_Price__c.field-meta.xml
<CustomField>
    <fullName>Retail_Price__c</fullName>
    <label>Retail Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project-01/force-app/main/default/objects/Sales_item__c/fields/Sales_Number__c.field-meta.xml
<CustomField>
    <fullName>Sales_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Number</label>
    <referenceTo>Sales__c</referenceTo>
    <relationshipLabel>Sales items</relationshipLabel>
    <relationshipName>Sales_items</relationshipName>
    <type>Lookup</type>
</CustomField>

Project01/force-app/main/default/objects/Sales_item__c/fields/T_J_Product__c.field-meta.xml
<CustomField>
    <fullName>T_J_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;J Product SKU</label>
    <referenceTo>ProductTJ__c</referenceTo>
    <relationshipLabel>Sales Details</relationshipLabel>
    <relationshipName>Sales_items</relationshipName>
    <type>Lookup</type>
</CustomField>

Project01/force-app/main/default/classes/SaleDetailsTriggerTest.cls
@isTest
public class SaleDetailsTriggerTest {
    @testSetup
    public static void setup(){

       
        
    }
    @isTest/* PositiveTest */
    public static void testChangingInventory(){

        Test.startTest();
         ProductTJ__c p1 = new ProductTJ__c(
            							  Description__c= 'Ring Diamonds', 
                                          Retail_Price1__c=230,
                                          Quantity__c = 24
                                         );
        insert p1;
        Account acct = new Account(Name='Test Account',	Email__c='acct@mail.com');
        insert acct;
        Sales__c s = new Sales__c(Account_Name__c=acct.Id, Total__c=345);
        insert s;
        
        Test.stopTest();
    }
    
    
    @isTest/* NegativeTest */
    public static void testCannotChangeProductInventory(){
       Test.startTest();
        try{
        	 Sales_item__c s = new Sales_item__c(Sales_Number__c= 'SA-0038', 
                                            T_J_Product__c='PR-0001', 
                                             Quantity__c = 30 ,   
                                             Retail_Price__c=230,Status__c='Completed'); 
            insert s;
        ProductTJ__c p = new ProductTJ__c (); 
        p = [SELECT Id,Quantity__c FROM ProductTJ__c WHERE Name =: 'PR-0001'];
            System.assertEquals(21,p.Quantity__c,'This is a negative Test');
            
        } catch(Exception e){
            System.assert(e.getMessage().contains('Something went wrong!'));
        }
        Test.stopTest();
    }
}