Project01/force-app/main/default/objects/ProductTJ__c/ProductTJ__c.object-meta.xml
<CustomObject>
    <description>my custom product object</description>
    <label>T&amp;J Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product SKU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;J Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project-01/force-app/main/default/objects/Sales_item__c/Sales_item__c.object-meta.xml
<CustomObject>
    <label>Sales item</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sales item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project-01/force-app/main/default/objects/Sales_item__c/fields/Sales_Number__c.field-meta.xml
<CustomField>
    <fullName>Sales_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Number</label>
    <referenceTo>Sales__c</referenceTo>
    <relationshipLabel>Sales items</relationshipLabel>
    <relationshipName>Sales_items</relationshipName>
    <type>Lookup</type>
</CustomField>

Project01/force-app/main/default/objects/Sales_item__c/fields/T_J_Product__c.field-meta.xml
<CustomField>
    <fullName>T_J_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;J Product SKU</label>
    <referenceTo>ProductTJ__c</referenceTo>
    <relationshipLabel>Sales Details</relationshipLabel>
    <relationshipName>Sales_items</relationshipName>
    <type>Lookup</type>
</CustomField>

Project01/force-app/main/default/classes/SaleDetailHandler.cls
public class SaleDetailHandler {
    
  //Flow took care of this too
    public static void CheckDuplicate(List<Sales_item__c> insertSalesItems) {

        List <Sales_item__c> myDuplicate = new List<Sales_item__c> ();
       
        
        for (Sales_item__c s : insertSalesItems) {
            
        myDuplicate = [SELECT Id FROM Sales_item__c
                     WHERE T_J_Product__c =: s.T_J_Product__c AND
                     Sales_Number__c =: s.Sales_Number__c];
			
            if(myDuplicate.Size()!=0){
            s.AddError('do not save Duplicate');
            }  
            else {
               
                ChangeProductInventory(insertSalesItems);
                
            }
        }   
            
    }     

    //Second Method
    public static void ChangeProductInventory(List<Sales_item__c> updateSalesItems) {
        
        List <ProductTJ__c> p = new List <ProductTJ__c> ();
        
        for (Sales_item__c s : updateSalesItems) {
            
        p = [SELECT Id,Quantity__c FROM ProductTJ__c WHERE Id =: s.T_J_Product__c AND Quantity__c >: s.Quantity__c];
                
                
                    
                    if(p.Size()==0){
            				s.AddError('Quantity exceded our inventory please place a special order');
            				}
            
            		else {
               				for (ProductTJ__c p1 :p){
                			p1.Quantity__c = (p1.Quantity__c - s.Quantity__c);
                	 		update p1;   
                
            				}
                }
 
            }
        }	
}