P01/force-app/main/default/objects/ProductTJ__c/ProductTJ__c.object-meta.xml
<CustomObject>
    <description>my custom product object</description>
    <label>T&amp;J Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product SKU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;J Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/ProductTJ__c/fields/Retail_Price1__c.field-meta.xml
<CustomField>
    <fullName>Retail_Price1__c</fullName>
    <label>Retail Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

P01/force-app/main/default/objects/Shopping_Cart__c/Shopping_Cart__c.object-meta.xml
<CustomObject>
    <label>Shopping Cart Item</label>
    <nameField>
        <displayFormat>SC - {0000}</displayFormat>
        <label>Shopping Cart Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shopping Carts Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/Shopping_Cart__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Shopping_Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

P01/force-app/main/default/objects/Shopping_Cart__c/fields/T_J_Product__c.field-meta.xml
<CustomField>
    <fullName>T_J_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;J Product</label>
    <referenceTo>ProductTJ__c</referenceTo>
    <relationshipLabel>Shopping Carts Items</relationshipLabel>
    <relationshipName>Shopping_Carts_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

P01/force-app/main/default/classes/AddToCartTest.cls
@isTest
public class AddToCartTest {
	
    @isTest
    static void testAddToCart(){
        Test.startTest();
        
        Account acct = new Account();
        acct.Name = 'TestAccount';
        acct.Email__c = 'test@test.com';
        
        insert acct;
        
        ProductTJ__c prod = new ProductTJ__c();
        prod.Description__c = 'Test Product';
        prod.Retail_Price1__c = 100;
        
        insert prod;
        
        AddToCart atc = new AddToCart();
        atc.prod = prod;
        atc.acct = acct;
        atc.addCartItem();
        
        List<Shopping_Cart__c> cartItems = Database.query('select name, account__r.name, t_j_product__r.description__c from shopping_cart__c where account__c = \'' + acct.Id + '\'');
        
            System.assertEquals(cartItems.isEmpty(), false);
            
        Test.stopTest();
    }
}