P01/force-app/main/default/objects/ProductTJ__c/ProductTJ__c.object-meta.xml
<CustomObject>
    <description>my custom product object</description>
    <label>T&amp;J Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product SKU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;J Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/ProductTJ__c/fields/Carat__c.field-meta.xml
<CustomField>
    <fullName>Carat__c</fullName>
    <label>Carat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

P01/force-app/main/default/objects/ProductTJ__c/fields/Product_Style__c.field-meta.xml
<CustomField>
    <fullName>Product_Style__c</fullName>
    <label>Product Style</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product_Style</valueSetName>
    </valueSet>
</CustomField>

Project-01/force-app/main/default/objects/ProductTJ__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Type</valueSetName>
    </valueSet>
</CustomField>

P01/force-app/main/default/objects/ProductTJ__c/fields/Retail_Price1__c.field-meta.xml
<CustomField>
    <fullName>Retail_Price1__c</fullName>
    <label>Retail Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

P01/force-app/main/default/globalValueSets/Product_Style.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bangle</fullName>
    </customValue>
    <customValue>
        <fullName>Chains</fullName>
    </customValue>
    <customValue>
        <fullName>Cluster</fullName>
    </customValue>
    <customValue>
        <fullName>Cocktail</fullName>
    </customValue>
    <customValue>
        <fullName>Cuff</fullName>
    </customValue>
    <customValue>
        <fullName>Dangle</fullName>
    </customValue>
    <customValue>
        <fullName>Drop</fullName>
    </customValue>
    <customValue>
        <fullName>Fashion</fullName>
    </customValue>
    <customValue>
        <fullName>Halo</fullName>
    </customValue>
    <customValue>
        <fullName>Hoop</fullName>
    </customValue>
    <customValue>
        <fullName>Lever back</fullName>
    </customValue>
    <customValue>
        <fullName>Pendant</fullName>
    </customValue>
    <customValue>
        <fullName>Solitaire</fullName>
    </customValue>
    <customValue>
        <fullName>Stud</fullName>
    </customValue>
    <customValue>
        <fullName>Tennis</fullName>
    </customValue>
    <masterLabel>Product Style</masterLabel>
</GlobalValueSet>

P01/force-app/main/default/globalValueSets/Product_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bracelets</fullName>
    </customValue>
    <customValue>
        <fullName>Earrings</fullName>
    </customValue>
    <customValue>
        <fullName>Necklaces</fullName>
    </customValue>
    <customValue>
        <fullName>Rings</fullName>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

P01/force-app/main/default/classes/GetProductsTest.cls
@isTest
public class GetProductsTest {
	@TestSetup
    public static void setup()
    {
        list<ProductTJ__c> products= new list<ProductTJ__c>();
        products.add(new ProductTJ__c( Carat__c=Integer.valueof((Math.random()*24)), 
                                          Product_Type__c='Rings', Product_Style__c='Halo', 
                                           Retail_Price1__c=(Math.random()*1000)));
        products.add(new ProductTJ__c(Carat__c=Integer.valueof((Math.random()*24)), 
                                          Product_Type__c='Bracelets', Product_Style__c='Bangle', 
                                           Retail_Price1__c=(Math.random()*1000)));
        products.add(new ProductTJ__c(Carat__c=Integer.valueof((Math.random()*24)), 
                                          Product_Type__c='Earrings', Product_Style__c='Hoop', 
                                           Retail_Price1__c=(Math.random()*1000)));
        products.add(new ProductTJ__c(Carat__c=Integer.valueof((Math.random()*24)), 
                                          Product_Type__c='Necklaces', Product_Style__c='Solitaire', 
                                           Retail_Price1__c=(Math.random()*1000)));
        products.add(new ProductTJ__c(Carat__c=Integer.valueof((Math.random()*24)), 
                                          Product_Type__c='Earrings', Product_Style__c='Drop', 
                                           Retail_Price1__c=(Math.random()*1000)));
        products.add(new ProductTJ__c(Carat__c=Integer.valueof((Math.random()*24)), 
                                          Product_Type__c='Rings', Product_Style__c='Cluster', 
                                           Retail_Price1__c=(Math.random()*1000)));
        
        insert products;
    }
    @isTest
    public static void getProductsTest()
    {

        list<ProductTJ__c> products = getProducts.getProducts('','','');
        system.assertEquals(6, products.size());
        /*
        products=getProducts.getProducts('PR-0000','','');
        system.assertEquals(1, products.size());
        products=getProducts.getProducts('PR-0000','Rings','');
        system.assertEquals(1, products.size());
        products=getProducts.getProducts('PR-0000','Bracelets','');
        system.assertEquals(0, products.size());
*/
        products=getProducts.getProducts('','Earrings','');
        system.assertEquals(2, products.size());
        products=getProducts.getProducts('','Earrings','Drop');
        system.assertEquals(1, products.size());
   /*     products=getProducts.getProducts('PR-0000','Rings','Halo');
        system.assertEquals(1, products.size());
*/
    }
}