P01/force-app/main/default/objects/ProductTJ__c/ProductTJ__c.object-meta.xml
<CustomObject>
    <description>my custom product object</description>
    <label>T&amp;J Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product SKU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;J Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/ProductTJ__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <type>TextArea</type>
</CustomField>

P01/force-app/main/default/objects/Shopping_Cart__c/Shopping_Cart__c.object-meta.xml
<CustomObject>
    <label>Shopping Cart Item</label>
    <nameField>
        <displayFormat>SC - {0000}</displayFormat>
        <label>Shopping Cart Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shopping Carts Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/Shopping_Cart__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Shopping_Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

P01/force-app/main/default/objects/Shopping_Cart__c/fields/T_J_Product__c.field-meta.xml
<CustomField>
    <fullName>T_J_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;J Product</label>
    <referenceTo>ProductTJ__c</referenceTo>
    <relationshipLabel>Shopping Carts Items</relationshipLabel>
    <relationshipName>Shopping_Carts_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

P01/force-app/main/default/objects/Shopping_Cart__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>Quantity__c  *  T_J_Product__r.Retail_Price1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

P01/force-app/main/default/classes/CartItemController.cls
public class CartItemController {
    /*       public List<Shopping_Cart__c> getcartItems(){
           List<Shopping_Cart__c> cartItems = [SELECT Account__r.Id,Name, Quantity__c, T_J_Product__c, Account__c,  Total_Amount__c , T_J_Product__r.Image__c FROM Shopping_Cart__c   ];
           return cartItems;
   */
       
       public Id accid{get;set;}
       Id id = apexpages.currentpage().getparameters().get('id');
       
       //return Cart items 
       List<Shopping_Cart__c> cartItems = [SELECT Name, Quantity__c, T_J_Product__c, Account__c,  Total_Amount__c , T_J_Product__r.Image__c FROM Shopping_Cart__c WHERE Account__r.ID =: id  ];
       public List<Shopping_Cart__c> getcartItems(){      
           return cartItems;
       }
   
   }