P01/force-app/main/default/objects/ProductTJ__c/ProductTJ__c.object-meta.xml
<CustomObject>
    <description>my custom product object</description>
    <label>T&amp;J Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product SKU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;J Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project-01/force-app/main/default/objects/ProductTJ__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Type</valueSetName>
    </valueSet>
</CustomField>

P01/force-app/main/default/objects/ProductTJ__c/fields/Retail_Price1__c.field-meta.xml
<CustomField>
    <fullName>Retail_Price1__c</fullName>
    <label>Retail Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

P01/force-app/main/default/objects/Shopping_Cart__c/Shopping_Cart__c.object-meta.xml
<CustomObject>
    <label>Shopping Cart Item</label>
    <nameField>
        <displayFormat>SC - {0000}</displayFormat>
        <label>Shopping Cart Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shopping Carts Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/Shopping_Cart__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Shopping_Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

P01/force-app/main/default/objects/Shopping_Cart__c/fields/T_J_Product__c.field-meta.xml
<CustomField>
    <fullName>T_J_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;J Product</label>
    <referenceTo>ProductTJ__c</referenceTo>
    <relationshipLabel>Shopping Carts Items</relationshipLabel>
    <relationshipName>Shopping_Carts_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

P01/force-app/main/default/globalValueSets/Product_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bracelets</fullName>
    </customValue>
    <customValue>
        <fullName>Earrings</fullName>
    </customValue>
    <customValue>
        <fullName>Necklaces</fullName>
    </customValue>
    <customValue>
        <fullName>Rings</fullName>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

P01/force-app/main/default/classes/CartItemTestClass.cls
@isTest
public class CartItemTestClass {
    /*@isTest 
    static void myCartItemTest(){
        Account testAcc = new Account();
        testAcc.Name = 'accT';
        insert testAcc;
            
        ProductTJ__c testProd = new ProductTJ__c();
        testProd.Product_Type__c = 'testProd';
        testProd.Retail_Price1__c = 100;
        insert testProd;
        
        Shopping_Cart__c testItem = new Shopping_Cart__c (
        							Account__c = testAcc.Id,
            						Quantity__c = 2,
        							T_J_Product__c = testProd.Name);
        insert testItem;
        
	Test.startTest();
       
//instantiate a page      
PageReference pageRef = Page.cart;
 //VF page name CartItemPage is the starting point of this test method      
 pageRef.getParameters().put('id',testItem.Id);
        Test.setCurrentPage(pageRef);    
     //   ApexPages.currentPage().getParameters().put('id',testItem.Id);
//instantiate and construct the controller class        
CartItemController c = new CartItemController();
        List<Shopping_Cart__c> sc =c.getcartItems();
        //pageRef.getParameters().put('id',testItem.Id)
  //      CartItemController.getcartItems()
  
	//ApexPages.StandardController sc = new ApexPages.standardController(testItem);
	
	Test.stopTest();
        
	System.assertEquals(1,sc.size());
}

*/
    }