P01/force-app/main/default/objects/ProductTJ__c/ProductTJ__c.object-meta.xml
<CustomObject>
    <description>my custom product object</description>
    <label>T&amp;J Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product SKU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;J Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/ProductTJ__c/fields/Carat__c.field-meta.xml
<CustomField>
    <fullName>Carat__c</fullName>
    <label>Carat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

P01/force-app/main/default/objects/ProductTJ__c/fields/Product_Style__c.field-meta.xml
<CustomField>
    <fullName>Product_Style__c</fullName>
    <label>Product Style</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product_Style</valueSetName>
    </valueSet>
</CustomField>

Project-01/force-app/main/default/objects/ProductTJ__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Type</valueSetName>
    </valueSet>
</CustomField>

P01/force-app/main/default/objects/ProductTJ__c/fields/Retail_Price1__c.field-meta.xml
<CustomField>
    <fullName>Retail_Price1__c</fullName>
    <label>Retail Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

P01/force-app/main/default/globalValueSets/Product_Style.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bangle</fullName>
    </customValue>
    <customValue>
        <fullName>Chains</fullName>
    </customValue>
    <customValue>
        <fullName>Cluster</fullName>
    </customValue>
    <customValue>
        <fullName>Cocktail</fullName>
    </customValue>
    <customValue>
        <fullName>Cuff</fullName>
    </customValue>
    <customValue>
        <fullName>Dangle</fullName>
    </customValue>
    <customValue>
        <fullName>Drop</fullName>
    </customValue>
    <customValue>
        <fullName>Fashion</fullName>
    </customValue>
    <customValue>
        <fullName>Halo</fullName>
    </customValue>
    <customValue>
        <fullName>Hoop</fullName>
    </customValue>
    <customValue>
        <fullName>Lever back</fullName>
    </customValue>
    <customValue>
        <fullName>Pendant</fullName>
    </customValue>
    <customValue>
        <fullName>Solitaire</fullName>
    </customValue>
    <customValue>
        <fullName>Stud</fullName>
    </customValue>
    <customValue>
        <fullName>Tennis</fullName>
    </customValue>
    <masterLabel>Product Style</masterLabel>
</GlobalValueSet>

P01/force-app/main/default/globalValueSets/Product_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bracelets</fullName>
    </customValue>
    <customValue>
        <fullName>Earrings</fullName>
    </customValue>
    <customValue>
        <fullName>Necklaces</fullName>
    </customValue>
    <customValue>
        <fullName>Rings</fullName>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

P01/force-app/main/default/classes/GetProducts.cls
public class GetProducts {
	@AuraEnabled
    public static list<ProductTJ__c> getProducts(string name, string type, string style)
    {
        String query ='SELECT Name, Carat__c, Product_Type__c, Product_Style__C, Retail_Price1__c FROM ProductTJ__c';
                   
        Boolean add = false;
        if(name!='' )
        {
            if(!add)
            {
                query+=' WHERE ';
            }
            query = query + 'Name LIKE :name';
            add=true;
        }
         if(type!='')
        {
            if(!add)
            {
                query+=' WHERE ';
            }
            if(add)
            {
                query+=' AND ';
            }
            query= query + ' Product_Type__c=:type';
            add=true;
            if(style!='')
            {
               
                query= query + ' AND Product_Style__c=:style' ;
            }
        }
        system.debug(query);
        list<ProductTJ__c> results = database.query(query);
        
        system.debug(results);
        return results;
    }  
}