P01/force-app/main/default/objects/ProductTJ__c/ProductTJ__c.object-meta.xml
<CustomObject>
    <description>my custom product object</description>
    <label>T&amp;J Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product SKU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;J Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/Shopping_Cart__c/Shopping_Cart__c.object-meta.xml
<CustomObject>
    <label>Shopping Cart Item</label>
    <nameField>
        <displayFormat>SC - {0000}</displayFormat>
        <label>Shopping Cart Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shopping Carts Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/Shopping_Cart__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Shopping_Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

P01/force-app/main/default/objects/Shopping_Cart__c/fields/T_J_Product__c.field-meta.xml
<CustomField>
    <fullName>T_J_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;J Product</label>
    <referenceTo>ProductTJ__c</referenceTo>
    <relationshipLabel>Shopping Carts Items</relationshipLabel>
    <relationshipName>Shopping_Carts_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

P01/force-app/main/default/classes/AddToCart.cls
public class AddToCart {
    public ProductTJ__c prod {get;set;}
    public Account acct {get; set;}
    
    public AddToCart(ApexPages.StandardController controller){
        prod = (ProductTJ__c)controller.getRecord();
        acct = [select id, name from account limit 1];
    }
    
    public AddToCart(){}
    
    public void addCartItem(){
        Shopping_Cart__c cartItem = new Shopping_Cart__c();
        cartItem.Account__c = acct.Id;
        cartItem.T_J_Product__c = prod.Id;
        cartItem.Quantity__c = 1;
        insert cartItem;
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Item added to cart.'));
    }
}