P01/force-app/main/default/objects/ProductTJ__c/ProductTJ__c.object-meta.xml
<CustomObject>
    <description>my custom product object</description>
    <label>T&amp;J Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product SKU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;J Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/ProductTJ__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trending</fullName>
            </value>
            <value>
                <fullName>New Arrival</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

P01/force-app/main/default/objects/ProductTJ__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <type>TextArea</type>
</CustomField>

Project-01/force-app/main/default/objects/ProductTJ__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Type</valueSetName>
    </valueSet>
</CustomField>

P01/force-app/main/default/objects/ProductTJ__c/fields/Retail_Price1__c.field-meta.xml
<CustomField>
    <fullName>Retail_Price1__c</fullName>
    <label>Retail Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

P01/force-app/main/default/globalValueSets/Product_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bracelets</fullName>
    </customValue>
    <customValue>
        <fullName>Earrings</fullName>
    </customValue>
    <customValue>
        <fullName>Necklaces</fullName>
    </customValue>
    <customValue>
        <fullName>Rings</fullName>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

P01/force-app/main/default/classes/ProductListControllerTest.cls
@isTest
public class ProductListControllerTest {

 
    //Each of the two test methods here gives a 83 test coverage
 @isTest static void testgetNewProducts(){
     
      ProductTJ__c p = new ProductTJ__c(Description__c= 'Diamonds studs', Retail_Price1__c=1200,Category__c='New Arrival');
       insert p;
       
     Test.StartTest();
     
List<ProductTJ__c> results = [SELECT Id, Description__c, Retail_Price1__c, Product_Type__c,Category__c,Image__c FROM ProductTJ__c WHERE Category__c=:'New Arrival'];
          
 
     Test.StopTest();
  
    
}
 @isTest static void testgetTrendingProducts(){
           
      ProductTJ__c p = new ProductTJ__c(Description__c= 'Diamonds studs', Retail_Price1__c=1200,Category__c='Trending');
       insert p;

       
     Test.StartTest();
     
          List<ProductTJ__c> results = [SELECT Id, Description__c, Retail_Price1__c, Product_Type__c,Category__c,Image__c FROM ProductTJ__c WHERE Category__c=:'Trending'];
          
 
     Test.StopTest();
  
    
}
 @isTest static void  testgetAllProducts(){
      
      ProductTJ__c p = new ProductTJ__c(Description__c= 'Diamonds studs', Retail_Price1__c=1200,Category__c='sale');
       insert p;
       
     Test.StartTest();
     
      List<ProductTJ__c> results = [SELECT Id, Description__c, Retail_Price1__c, Product_Type__c,Category__c,Image__c FROM ProductTJ__c WHERE Category__c=:'Sale'];
          
 
 
     Test.StopTest();
  
    
}
}