P01/force-app/main/default/objects/Return_Sale__c/Return_Sale__c.object-meta.xml
<CustomObject>
    <label>Return</label>
    <nameField>
        <displayFormat>RE-{0000}</displayFormat>
        <label>Return Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/Return_Sale__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Returns</relationshipLabel>
    <relationshipName>Returns</relationshipName>
    <type>Lookup</type>
</CustomField>

Project-01/force-app/main/default/objects/Return_Sale__c/fields/Sales_Number__c.field-meta.xml
<CustomField>
    <fullName>Sales_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Number</label>
    <referenceTo>Sales__c</referenceTo>
    <relationshipLabel>Returns</relationshipLabel>
    <relationshipName>Returns</relationshipName>
    <type>Lookup</type>
</CustomField>

P01/force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>Sale</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Sales Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/Sales__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales</relationshipLabel>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

Project-01/force-app/main/default/objects/Sales__c/fields/Sales_Associate_Id__c.field-meta.xml
<CustomField>
    <fullName>Sales_Associate_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Associate</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

Project01/force-app/main/default/objects/Sales__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

P01/force-app/main/default/classes/SalesObjectTriggerTest.cls
@isTest
public class SalesObjectTriggerTest {
    @isTest/* PositiveTest */
    public static void testDeleteSaleWithoutReturn(){
     Test.startTest();
        // Creer account dummy data
        Account acct = new Account(Name='Test Account',	Email__c='acct@mail.com');
        insert acct;
        Sales__c s = new Sales__c(Account_Name__c=acct.Id, Total__c=345);
        insert s;
        try{
            Database.DeleteResult result = Database.delete(s, false);
            System.assertEquals('It should work damn it!',
                             result.getErrors()[0].getMessage()); 
        }catch (Exception e) {
            
			e.getTypeName();
            
        }
        
        Test.stopTest();
        // Verify 
        // In this case the deletion should have been stopped by the trigger,
        // so verify that we got back an error.
        //System.assert(!result.isSuccess());
        //System.assert(result.getErrors().size() > 0);
        //System.assertEquals('Cannot delete account with related return.',
                            // result.getErrors()[0].getMessage()); 
    }
   @isTest // Negative Test
    public static void testDeleteSaleWithReturn(){
        Test.startTest();
        // Creer account dummy data
        Account acct = new Account(Name='Test Account',	Email__c='acct@mail.com');
        insert acct;
        // Test data setup
        // Creer sales dummy data
        Sales__c s = new Sales__c(Account_Name__c=acct.Id,Sales_Associate_Id__c='0055e0000057ABzAAM', Total__c=345);
        insert s;
        Return_Sale__c r = new Return_Sale__c(Account_Name__c=s.Account_Name__c,
                                              Sales_Number__c=s.Name,
                                              Return_Date__c=System.today());
                                       //Return_Date__c=System.today().addMonths(1),
                                       //AccountId=acct.Id);
        insert r;
        Database.DeleteResult result = Database.delete(s, false);
        Test.stopTest();
        // Verify 
        // In this case the deletion should have been stopped by the trigger,
        // so verify that we got back an error.
        System.assert(!result.isSuccess());
        System.assert(result.getErrors().size() > 0);
        System.assertEquals('Cannot delete account with related return.',
                             result.getErrors()[0].getMessage());
    }
}