P01/force-app/main/default/objects/Return_Sale__c/Return_Sale__c.object-meta.xml
<CustomObject>
    <label>Return</label>
    <nameField>
        <displayFormat>RE-{0000}</displayFormat>
        <label>Return Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project-01/force-app/main/default/objects/Return_Sale__c/fields/Sales_Number__c.field-meta.xml
<CustomField>
    <fullName>Sales_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Number</label>
    <referenceTo>Sales__c</referenceTo>
    <relationshipLabel>Returns</relationshipLabel>
    <relationshipName>Returns</relationshipName>
    <type>Lookup</type>
</CustomField>

P01/force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>Sale</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Sales Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project-01/force-app/main/default/objects/Sales_item__c/Sales_item__c.object-meta.xml
<CustomObject>
    <label>Sales item</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sales item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project-01/force-app/main/default/objects/Sales_item__c/fields/Sales_Number__c.field-meta.xml
<CustomField>
    <fullName>Sales_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Number</label>
    <referenceTo>Sales__c</referenceTo>
    <relationshipLabel>Sales items</relationshipLabel>
    <relationshipName>Sales_items</relationshipName>
    <type>Lookup</type>
</CustomField>

P01/force-app/main/default/classes/SalesObjectHandler.cls
public class SalesObjectHandler {

//update sales status when return acquire    
public static void CheckForChildRecord(List<Sales__c> updateSales) {

    List <Sales_item__c> MychildList  = new List<Sales_item__c> ();
    List <Return_Sale__c> MychildList2  = new List<Return_Sale__c> ();
    
        
        for (Sales__c s : updateSales) {
            
        //sales item table    
        MychildList = [SELECT Id FROM Sales_item__c
                     WHERE Sales_Number__c =: s.Name];
        		
         //Return table    
        MychildList2 = [SELECT Id FROM Return_Sale__c
                     WHERE Sales_Number__c =: s.Name];
   
            //delete sale only if it has not been return            
            if(MychildList2.Size()!=0){
            s.AddError('Can not delete the sale');
            }  
            else {
                delete MychildList;
                delete s;
                
            }
        }   
}
    
    public static void ChangeStatus(List<Sales__c> updateSales) {

    List <Sales_item__c> MychildList  = new List<Sales_item__c> ();
    //List <Return_Sale__c> MychildList2  = new List<Return_Sale__c> ();
    
        
        for (Sales__c s : updateSales) {
            
         
}
    
}
}