P01/force-app/main/default/objects/Commision__c/Commision__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>COM-{0000}</displayFormat>
        <label>Commision Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/Commision__c/fields/Commision_Period__c.field-meta.xml
<CustomField>
    <fullName>Commision_Period__c</fullName>
    <label>Commision Period</label>
    <type>Date</type>
</CustomField>

Project01/force-app/main/default/objects/Commision__c/fields/Sales_Associate__c.field-meta.xml
<CustomField>
    <fullName>Sales_Associate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Associate</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Commissions1</relationshipName>
    <type>Lookup</type>
</CustomField>

Project-01/force-app/main/default/objects/Commision__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

P01/force-app/main/default/objects/Commision__c/recordTypes/A.recordType-meta.xml
<RecordType>
    <fullName>A</fullName>
    <active>true</active>
    <label>A</label>
</RecordType>

P01/force-app/main/default/objects/ProductTJ__c/ProductTJ__c.object-meta.xml
<CustomObject>
    <description>my custom product object</description>
    <label>T&amp;J Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Product SKU</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>T&amp;J Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P01/force-app/main/default/objects/Sales__c/Sales__c.object-meta.xml
<CustomObject>
    <label>Sale</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Sales Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project-01/force-app/main/default/objects/Sales__c/fields/Sales_Associate_Id__c.field-meta.xml
<CustomField>
    <fullName>Sales_Associate_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Associate</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

Project01/force-app/main/default/objects/Sales__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project-01/force-app/main/default/objects/Sales_item__c/Sales_item__c.object-meta.xml
<CustomObject>
    <label>Sales item</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Sales item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project01/force-app/main/default/objects/Sales_item__c/fields/Commision_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commision_Amount__c</fullName>
    <formula>Commision_rate__c  *  Subtotal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commision Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Project-01/force-app/main/default/objects/Sales_item__c/fields/Sales_Number__c.field-meta.xml
<CustomField>
    <fullName>Sales_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Number</label>
    <referenceTo>Sales__c</referenceTo>
    <relationshipLabel>Sales items</relationshipLabel>
    <relationshipName>Sales_items</relationshipName>
    <type>Lookup</type>
</CustomField>

Project01/force-app/main/default/objects/Sales_item__c/fields/T_J_Product__c.field-meta.xml
<CustomField>
    <fullName>T_J_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>T&amp;J Product SKU</label>
    <referenceTo>ProductTJ__c</referenceTo>
    <relationshipLabel>Sales Details</relationshipLabel>
    <relationshipName>Sales_items</relationshipName>
    <type>Lookup</type>
</CustomField>

P01/force-app/main/default/classes/SaleDetailHandler.cls
public class SaleDetailHandler {
    
  //Flow took care of this too
    public static void CheckDuplicate(List<Sales_item__c> insertSalesItems) {

        List <Sales_item__c> myDuplicate = new List<Sales_item__c> ();
       
        
        for (Sales_item__c s : insertSalesItems) {
            
        myDuplicate = [SELECT Id FROM Sales_item__c
                     WHERE T_J_Product__c =: s.T_J_Product__c AND
                     Sales_Number__c =: s.Sales_Number__c];
			
            if(myDuplicate.Size()!=0){
            s.AddError('do not save Duplicate');
            }  
            else {
               
                ChangeProductInventory(insertSalesItems);
                
            }
        }   
            
    }  
    
    
    //Second Method
    public static void ChangeProductInventory(List<Sales_item__c> updateSalesItems) {
        
        List <ProductTJ__c> p = new List <ProductTJ__c> ();
        List <Commision__c> Listcomm = new List <Commision__c> ();
        Sales__c assc = new Sales__c ();
        
        
        for (Sales_item__c s : updateSalesItems) {
 		assc = [SELECT Id, Sales_Associate_Id__c FROM Sales__c WHERE Id =: s.Sales_Number__c];
        //Creates brain new commission
       //check if comm for sales associate existe 
       
        Listcomm = [SELECT Id,Total_Amount__c FROM Commision__c WHERE Sales_Associate__c =: assc.Sales_Associate_Id__c AND Status__c='Active' ]; 
        
            if (Listcomm.size()==0){
                
                Commision__c myc = new Commision__c(Commision_Period__c=System.today(),
                                            Sales_Associate__c=assc.Sales_Associate_Id__c,
                                            Total_Amount__c=s.Commision_Amount__c,
                                           	Status__c='Active');

            insert myc;
            
            }
            
            else {
                
                for(Commision__c l:Listcomm){
                    
				Commision__c ob = new Commision__c();                    
                    
                   ob.Total_Amount__c = l.Total_Amount__c + s.Commision_Amount__c ;
                   ob.Sales_Associate__c = assc.Sales_Associate_Id__c;
                   ob.Id = l.Id ;
                    
                   update ob;
                    
                }
                
                
            }
            
        
		
       // myc.add(s.Commision_Amount__c);
            
        p = [SELECT Id,Quantity__c FROM ProductTJ__c WHERE Id =: s.T_J_Product__c AND Quantity__c >: s.Quantity__c];
                
                
                    
                    if(p.Size()==0){
            				s.AddError('Quantity exceded our inventory please place a special order');
            				}
            
            		else {
               				for (ProductTJ__c p1 :p){
                			p1.Quantity__c = (p1.Quantity__c - s.Quantity__c);
                	 		update p1;   
                
            				}
                }
 
            }
        }	
}